Fix failing builds due to old gulp-less version
The version of gulp-less getting installed by ^2.0.1 

node_modules/gulp-less/index.js:68 
    }).done(undefined, cb);
       ^
TypeError: undefined is not a function